default_language_version:
    python: python3.8
repos:
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.782
        hooks:
        -   id: mypy
            args: [--ignore-missing-imports]
    -   repo: https://github.com/psf/black
        rev: 19.3b0
        hooks:
        -   id: black
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        -   id: flake8
            args: [--max-line-length=150]
    -   repo: https://github.com/PyCQA/bandit
        rev: 1.6.2
        hooks:
        -   id: bandit
            args: [--verbose]